Magazzino/Models/Anagrafica.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Magazzino.Models
{
    public partial class Anagrafica
    {
        public int Id { get; set; }
        [DisplayName("Codice")]
        [Remote(controller: "Anagrafica", action: "ValidateCodice", ErrorMessage = "Codice articolo già in uso.")]
        public string Codice { get; set; }
        public string Descrizione { get; set; }
        public string Note { get; set; }
    }
}

Magazzino/Models/CarrelliController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Magazzino.Models
{
    public class CarrelliController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Magazzino/Models/ErrorViewModel.cs
using System;

namespace Magazzino.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Magazzino/Models/MagazzinoContext.cs
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Magazzino.Models
{
    public partial class MagazzinoContext : DbContext
    {
        public MagazzinoContext()
        {
        }

        public MagazzinoContext(DbContextOptions<MagazzinoContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Anagrafica> Anagrafica { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. See http://go.microsoft.com/fwlink/?LinkId=723263 for guidance on storing connection strings.
                optionsBuilder.UseSqlServer("Server=DESKTOP-HT0MQRV;Database=Magazzino;Trusted_Connection=True;");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Anagrafica>(entity =>
            {
                entity.Property(e => e.Codice)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.Descrizione)
                    .IsRequired()
                    .HasMaxLength(250);

                entity.Property(e => e.Note).HasMaxLength(250);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}

Magazzino/Controllers/AnagraficaController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using Magazzino.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using X.PagedList;
using System.Threading;
using Microsoft.AspNetCore.Mvc.RazorPages;


namespace Magazzino.Controllers
{
    public class AnagraficaController : Controller
    {
        MagazzinoContext entities = new MagazzinoContext();
        private MagazzinoContext magazzinoContext;
        public AnagraficaController(MagazzinoContext magazzinoContext)
        {
            this.magazzinoContext = magazzinoContext;
        }
        public async Task<IActionResult> Index(string searchString, int? page)
        {
            ViewBag.CurrentSort = searchString;
            ViewBag.NoteSortParm = searchString == "note" ? "note_desc" : "note";
            ViewBag.DescrizioneSortParm = searchString == "descrizione" ? "descrizione_desc" : "descrizione";
            ViewBag.CodiceSortParm = String.IsNullOrEmpty(searchString) ? "codice_desc" : "";
            var articolo = from q in magazzinoContext.Anagrafica select q;
            if (!String.IsNullOrEmpty(searchString))
            {
                articolo = articolo.Where(q => q.Codice.Contains(searchString) || q.Descrizione.Contains(searchString)
                || q.Note.Contains(searchString));
            }
            
            int pageSize = 5;
            int pageNumber = (page ?? 1);
            return View(articolo.ToPagedList(pageNumber, pageSize));
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("Id,Codice,Descrizione,Note")] Anagrafica articolo)
        {
            if (ModelState.IsValid)
            {

                magazzinoContext.Add(articolo);
                magazzinoContext.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(articolo);
        }
        public async Task<IActionResult> Details(int? Id)
        {
            if (Id == null)
            {
                return NotFound();
            }

            var articolo = await magazzinoContext.Anagrafica.FindAsync(Id);
            if (articolo == null)
            {
                return NotFound();
            }

            return View(articolo);
        }
        public async Task<IActionResult> Edit(int? Id)
        {
            if (Id == null)
            {
                return NotFound();
            }

            var articolo = await magazzinoContext.Anagrafica.FindAsync(Id);
            if (articolo == null)
            {
                return NotFound();
            }
            return View(articolo);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int Id, [Bind("Id,Codice,Descrizione,Note")] Anagrafica articolo) 
        {
            if (Id != articolo.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    magazzinoContext.Update(articolo);
                    await magazzinoContext.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ItemExists(articolo.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(articolo);
        }
        public async Task<IActionResult> Delete(int? Id)
        {
            if (Id == null)
            {
                return NotFound();
            }

            var articolo = await magazzinoContext.Anagrafica.FindAsync(Id);
            if (articolo == null)
            {
                return NotFound();
            }

            return View(articolo);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int Id)
        {
            var articolo = await magazzinoContext.Anagrafica.FindAsync(Id);
            magazzinoContext.Anagrafica.Remove(articolo);
            await magazzinoContext.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        private bool ItemExists(int Id)
        {
            return magazzinoContext.Anagrafica.Any(e => e.Id == Id);
        }
        public  IActionResult ValidateCodice([Bind(Prefix = "Codice")] string stringaDaValidare)
        {
            var codici = from t in entities.Anagrafica select t.Codice;
            foreach (string codice in codici)
            {
                if (codice == stringaDaValidare)
                {
                    return Json(false);
                }
            }
            return Json(true);
        }
    }
}
 

Magazzino/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Magazzino.Models;

namespace Magazzino.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }
       
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Magazzino/Views/Anagrafica/Create.cshtml
@model Magazzino.Models.Anagrafica
@{
    ViewBag.Title = "Nuovo Articolo";
}

<h2>@ViewData["Title"]</h2>
<div class="row">
    <div class="col-md-4">
        <form asp-controller="Anagrafica" asp-action="Create" method="post" class="text-danger" role="form">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Codice" class="control-label"></label>
                <input asp-for="Codice" class="form-control" required="required" />
                <span asp-validation-for="Codice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descrizione" class="control-label"></label>
                <input asp-for="Descrizione" class="form-control" required="required" />
                <span asp-validation-for="Descrizione" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Note" class="control-label"></label>
                <input asp-for="Note" class="form-control"  />
                <span asp-validation-for="Note" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Magazzino/Views/Anagrafica/Delete.cshtml
@model Magazzino.Models.Anagrafica

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Item</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Codice)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Codice)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Descrizione)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Descrizione)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Note)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Note)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Magazzino/Views/Anagrafica/Details.cshtml
@model Magazzino.Models.Anagrafica
@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Item</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Codice)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Codice)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Descrizione)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Descrizione)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Note)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Note)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Magazzino/Views/Anagrafica/Edit.cshtml
@model Magazzino.Models.Anagrafica
@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Item</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Codice" class="control-label"></label>
                <input asp-for="Codice" class="form-control" />
                <span asp-validation-for="Codice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descrizione" class="control-label"></label>
                <input asp-for="Descrizione" class="form-control" />
                <span asp-validation-for="Descrizione" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Note" class="control-label"></label>
                <input asp-for="Note" class="form-control" />
                <span asp-validation-for="Note" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Magazzino/Views/Anagrafica/Index.cshtml
@model IPagedList<Magazzino.Models.Anagrafica>
@using X.PagedList;
@using X.PagedList.Mvc.Core;
@{
    ViewBag.Title = "Anagrafica";
}
<h2>Anagrafica</h2>
<p>
    <a asp-controller="Anagrafica" asp-action="Create">Create New</a>
</p>
@using (Html.BeginForm("Index", "Anagrafica", FormMethod.Get))
{
    <p>
        Ricerca articolo: @Html.TextBox("searchString")
        <input type="submit" value="Search" class="btn btn-primary" />
    </p>
}
<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th>Codice</th>
            <th>Descrizione</th>
            <th>Note</th>
            <th></th>
        </tr>
    <thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Codice)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Descrizione)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Note)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id"><i class="fa fa-pencil fa-fw"></i></a> 
                    <a asp-action="Details" asp-route-id="@item.Id"><i class="fa fa-search"></i></a> 
                    <a asp-action="Delete" asp-route-id="@item.Id"><i class="fa fa-trash-o"></i></a>
                </td>
            </tr>
        }
    </tbody>
</table>
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, currentFilter = ViewBag.CurrentFilter, searchString = ViewBag.CurrentSort }))

Magazzino/Views/Carrelli/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<p>First Name: <input data-bind="value: firstName" /></p>
<p>First Name: <input data-bind="value: lastName" /></p>
<div data-bind="visible: shouldShowMessage">
    <p>Full Name: <span data-bind="text: fullName"></span></p>
</div>
<button class="btn btn-success" data-bind="click: saluto">Saluto!</button>

@section Scripts {
    <script>
        var viewModel = {
            firstName: ko.observable("Manuel"),
            lastName: ko.observable("Rodriguez"),
            shouldShowMessage: ko.observable(true),
            saluto: function () {
                alert("Ciao Utente!! chiamami => +393349980678");
            }
        };
        viewModel.fullName = ko.dependentObservable(function () {
            return this.firstName() + " " + this.lastName();
        }, viewModel);
        ko.applyBindings(viewModel);
    </script>
}

Magazzino/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

    <div class="text-center">
        <h1 class="display-4">Benvenuto nel tuo Magazzino!</h1>
        <img src="magazzino.jpg" class="rounded img-fluid">
    </div>

Magazzino/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Magazzino</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/font-awesome-4.7.0/css/font-awesome.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AppMagazzino</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Anagrafica" asp-action="Index">Anagrafica Articoli</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Carrelli" asp-action="Index">knockoutjs</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Magazzino - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/knockout-3.5.1.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>